import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class", '[data-theme="dark"]'],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: "1rem",
        sm: "1.5rem",
        lg: "2rem",
        xl: "2.5rem",
        "2xl": "3rem",
      },
      screens: {
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1400px",
        xs: "475px",
      },
    },
    screens: {
      xs: "475px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    extend: {
      spacing: {
        1: "4px",
        2: "8px",
        3: "12px",
        4: "16px",
        5: "20px",
        6: "24px",
        8: "32px",
        10: "40px",
        12: "48px",
        16: "64px",
        18: "4.5rem",
        20: "80px",
        24: "96px",
        32: "128px",
        88: "22rem",
      },
      fontSize: {
        "2xs": ["0.625rem", { lineHeight: "0.75rem" }],
        xs: ["12px", { lineHeight: "16px" }],
        sm: ["14px", { lineHeight: "20px" }],
        base: ["16px", { lineHeight: "24px" }],
        lg: ["18px", { lineHeight: "28px" }],
        xl: ["20px", { lineHeight: "28px" }],
        "2xl": ["24px", { lineHeight: "32px" }],
        "3xl": ["30px", { lineHeight: "36px" }],
        "4xl": ["36px", { lineHeight: "40px" }],
        "5xl": ["48px", { lineHeight: "52px" }],
        "6xl": ["64px", { lineHeight: "68px" }],
      },
      fontFamily: {
        primary: ["Open Sans", "system-ui", "-apple-system", "Segoe UI", "sans-serif"],
        mono: ["JetBrains Mono", "Courier New", "monospace"],
      },
      fontWeight: {
        regular: "400",
        medium: "500",
        semibold: "600",
        bold: "700",
      },
      letterSpacing: {
        tight: "-0.02em",
        normal: "0",
        wide: "0.02em",
        wider: "0.05em",
      },
      minHeight: {
        touch: "44px",
      },
      minWidth: {
        touch: "44px",
      },
      colors: {
        primary: {
          50: "#f0f8ff",
          100: "#e0efff",
          200: "#b8ddff",
          300: "#90cbff",
          400: "#68b9ff",
          500: "#0070d5",
          600: "#0056a3",
          700: "#003d71",
          800: "#00243f",
          900: "#000b0f",
          DEFAULT: "#0070d5",
          foreground: "#ffffff",
        },
        neutral: {
          50: "#ffffff",
          100: "#fafafa",
          200: "#f2f2f2",
          300: "#eeeeed",
          400: "#ededed",
          500: "#919699",
          600: "#6c7073",
          700: "#616466",
          800: "#3c3e40",
          900: "#303233",
        },
        background: {
          primary: "hsl(var(--background-primary))",
          secondary: "hsl(var(--background-secondary))",
          elevated: "hsl(var(--background-elevated))",
          overlay: "hsl(var(--background-overlay))",
        },
        foreground: {
          primary: "hsl(var(--foreground-primary))",
          secondary: "hsl(var(--foreground-secondary))",
          muted: "hsl(var(--foreground-muted))",
        },
        semantic: {
          success: "#10b981",
          warning: "#f59e0b",
          error: "#ef4444",
          info: "#3b82f6",
        },
        border: {
          DEFAULT: "hsl(var(--border-primary))",
          primary: "hsl(var(--border-primary))",
          secondary: "hsl(var(--border-secondary))",
        },
        input: "hsl(var(--border-secondary))",
        ring: "hsl(var(--foreground-muted))",
        accent: {
          DEFAULT: "#3b63a9",
          foreground: "#ffffff",
        },
        secondary: {
          DEFAULT: "#232323",
          foreground: "#ffffff",
        },
        success: "#10b981",
        error: "#ef4444",
        warning: "#f59e0b",
        destructive: {
          DEFAULT: "hsl(var(--foreground-muted))",
          foreground: "#ffffff",
        },
        muted: {
          DEFAULT: "hsl(var(--foreground-muted) / 0.15)",
          foreground: "hsl(var(--foreground-muted))",
        },
        popover: {
          DEFAULT: "hsl(var(--background-elevated))",
          foreground: "hsl(var(--foreground-primary))",
        },
        card: {
          DEFAULT: "hsl(var(--background-secondary))",
          foreground: "hsl(var(--foreground-primary))",
        },
      },
      borderRadius: {
        xs: "2px",
        sm: "4px",
        base: "6px",
        md: "8px",
        lg: "var(--radius)",
        xl: "24px",
        pill: "60px",
        "pill-md": "64px",
        "pill-lg": "99px",
        "pill-xl": "999px",
        "pill-xxl": "1408px",
        full: "9999px",
        "legacy-md": "calc(var(--radius) - 2px)",
        "legacy-sm": "calc(var(--radius) - 4px)",
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        directional: "var(--shadow-directional)",
        elevated: "var(--shadow-elevated)",
        card: "var(--shadow-card)",
        "card-hover": "var(--shadow-card-hover)",
        modal: "var(--shadow-modal)",
        "glow-blue": "var(--shadow-glow-blue)",
      },
    },
  },
  plugins: [],
};

export default config;
